networks:
  adm_live_demo:
    external: true # Use an existing external network (always use that)

services:
  mqtt:
    image: hivemq/hivemq4:dns-latest
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8883:8883" # Mqtt over ssl port
    volumes:
      - ./hivemq-data:/opts/hivemq/data
    networks:
      - adm_live_demo
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

# redis
  redis:
    image: redis/redis-stack:latest
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight port
    volumes:
      - ./redis-data:/data
    networks:
      - adm_live_demo
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

  redis_hydration:
    image: docker.redpanda.com/redpandadata/connect:latest
    container_name: redis_hydration
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mqtt
      - redis
    networks:
      - adm_live_demo
    volumes:
      - ./redis_hydration.yaml:/connect.yaml