input:
  label: "mqtt_in"
  mqtt:
    urls:
      - "mqtt://mqtt_broker:1883"
    client_id: "redis-hydration-18e694e4-6eb7-4298-bc60-f3553b151885"
    keepalive: 60
    clean_session: true
    topics:
      - "pohl-industries/+/machines/+/telemetry/#"

pipeline:
  processors:
    - mapping: |
        root = this
        let parts = meta("mqtt_topic").split("/")
        root.field = $parts.index(-1)              
        meta key = $parts.index(3)                 
    - mapping: |
        root = { this.field: this.value.string() }

output:
  label: "redis_out"
  redis_hash:
    url: "redis://redis_container:6379"
    key: ${! meta("key") }  
    walk_metadata: false
    walk_json_object: true

logger:
  level: DEBUG
  format: logfmt